#!/bin/bash
## Logging functions
INFO(){ echo "INFO: $*"; }
WARN(){ echo "WARN: $*"; }
ERRO(){ echo "ERRO: $*"; exit 1; }

## Check some deps
bin_exist(){ command -v "$1" &> /dev/null || ERRO "Missing ${1}!"; }
for bin in wine winetricks wineserver winepath wineboot wget; do
    bin_exist $bin
done

## Define useful functions
rm_w(){ [ -f "$1" ] && rm "$1"; }

## Some vars
export PREFIXCOMMAND TMP BASE_DIR

export WINEPREFIX WINEARCH
export WINE_REQ_MOD=( dotnet45 )
export OSU_INSTALL_PATH

CONF=/etc/osu-wine.conf
TMP="$(mktemp -u)"

## Initialization
# shellcheck source=osu-wine.conf
source "$CONF" &> /dev/null || ERRO "Missing: ${CONF}!"

[ -z "$WINEARCH" ]         && WINEARCH=win32
[ -z "$BASE_DIR" ]         && BASE_DIR="$HOME/.local/share/osu-wine"
[ -z "$WINEPREFIX" ]       && WINEPREFIX="$BASE_DIR/WINE.$WINEARCH/"
[ -z "$OSU_INSTALL_PATH" ] && OSU_INSTALL_PATH="$BASE_DIR/OSU/"

{
    INFO "Check: Base dir $BASE_DIR"
    mkdir -p "$BASE_DIR"
}

{
    INFO "Check: wineprefix exist $WINEPREFIX"
    if [ ! -d "$WINEPREFIX" ]; then
        INFO "Wine prefix not exist"
        INFO "So try recreate it"
        wineboot &> /dev/null
        INFO "Created: $WINEPREFIX"
    fi
    INFO "Last tested version: wine-2.16"
    INFO "Your version: $(wine --version)"
}

{
    INFO "Check: wineprefix configured"
    cd "$WINEPREFIX" || exit 1
    if [ ! -f "winetricks.log" ]; then
        winetricks -q --optout "${WINE_REQ_MOD[@]}" || ERRO "Something went wrong!"
    fi
}

{
    INFO "Check: wine can access only to wine drive C:/ + X:/ (osu)"
    for link in "$WINEPREFIX/dosdevices"/*; do
        [[ "$link" =~ c: ]] && continue # For default link to ../drive_c
        [[ "$link" =~ x: ]] && continue # For link to osu path
        rm -v "$link"
    done
}

{
    INFO "Check: osu dir"
    mkdir -p "$OSU_INSTALL_PATH"
}

{
    INFO "Check: Link X: -> $OSU_INSTALL_PATH"
    ln -Tfs "$OSU_INSTALL_PATH" "$WINEPREFIX/dosdevices/x:"
}

cd "$OSU_INSTALL_PATH" || exit 1

{
    if [ ! -f "osu!.exe" ]; then
        INFO "Can't find osu exe, reinstall"
        wget http://m1.ppy.sh/r/osu!install.exe -O "osu!.exe"
    fi
}

INFO "Initialization Finished"

if [ -f "$1" ]; then
    mv -v "$1" ./
    for file in ./*.osz ./*.osz2 ./*.osr ./*.osk; do
        [ ! -f "$file" ] && continue
        $PREFIXCOMMAND wine "X:/osu!.exe" "$file"
    done
    exit 0
else
    $PREFIXCOMMAND wine "X:/osu!.exe"
fi
